import { Layout } from 'antd'
import { Content } from 'antd/lib/layout/layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import UserList from '../components/UserList'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>NewRoots</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Content className='home-content'>
        <UserList/>
      </Content>
    </Layout>
  )
}

export default Home
